### ISSUE TITLE
Display of Date in Dashboard 

### ISSUE THREAD

**Issue by RuijingZ** [MoH-Malaysia/kkmnow-data#1]
Hi MoH Team,

I recognized that dashboard changed to a new website: https://data.moh.gov.my/covid
However, the new display is a little vague on which date is these data referring to. There is only 'Last updated' time for each part, but no 'Data as of'.
![image](https://user-images.githubusercontent.com/68354122/195382084-29258f91-3a9c-4e20-b429-6dafa1c79460.png)

 I believe the 'Last udpdated' date does not refer to the actual reference date. Could you also include the reference date for these data? 

Thanks!

**Comment by MoH-Malaysia** [comment]
Thank you for the feedback - we have now updated all pages to show a "Last Updated" timestamp (for the page deployment) as well as a "Data as of" timestamp.
